version: "3.8"

services:
  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBIT_DEFAULT_USER=guest
      - RABBIT_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'